title: Plant Noma
email: hello@plantnoma.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Giving you the opportunity to keep your hands dirty through City Gardening. Weekly workshops explore horticulture through the widest possible lens 🌿
url: "https://plantnoma.co.uk" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink: pretty 
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
